// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0K46Eph5a6beADkN9Wa5nsC_fYRWhwLk',
    appId: '1:251085162608:android:b24e129ffbd608101fccb5',
    messagingSenderId: '251085162608',
    projectId: 'safedrive-f7c49',
    storageBucket: 'safedrive-f7c49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO5C9kWSfUWXF4esoKi3QKuViUeth5JvU',
    appId: '1:251085162608:ios:a55bfd610c86b7961fccb5',
    messagingSenderId: '251085162608',
    projectId: 'safedrive-f7c49',
    storageBucket: 'safedrive-f7c49.appspot.com',
    iosBundleId: 'lk.dilshan.safedrive',
  );
}
//
// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
//
// import 'package:firebase_core/firebase_core.dart';
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDFbZNlWVPsLq6fQ8kuAKp8YhP1DPFmxUU',
//     appId: '1:130526018894:web:c8c1dee6b024bd6e3ff21f',
//     messagingSenderId: '130526018894',
//     projectId: 'safedrive-3f52e',
//     authDomain: 'safedrive-3f52e.firebaseapp.com',
//     storageBucket: 'safedrive-3f52e.appspot.com',
//     measurementId: 'G-7M8C0DW8H2',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB0zLaD7zvgF4mlwY6evhpd2YBmhuzlKtI',
//     appId: '1:130526018894:android:87f6ded2efabfe3b3ff21f',
//     messagingSenderId: '130526018894',
//     projectId: 'safedrive-3f52e',
//     storageBucket: 'safedrive-3f52e.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDpJLsC9CWyNmRmtWU4ifE4b5BEaCLKUFk',
//     appId: '1:130526018894:ios:4fb1ff50720e71e13ff21f',
//     messagingSenderId: '130526018894',
//     projectId: 'safedrive-3f52e',
//     storageBucket: 'safedrive-3f52e.appspot.com',
//     iosBundleId: 'com.example.safeDiveApp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDpJLsC9CWyNmRmtWU4ifE4b5BEaCLKUFk',
//     appId: '1:130526018894:ios:4fb1ff50720e71e13ff21f',
//     messagingSenderId: '130526018894',
//     projectId: 'safedrive-3f52e',
//     storageBucket: 'safedrive-3f52e.appspot.com',
//     iosBundleId: 'com.example.safeDiveApp',
//   );
// }
