name: "Build & Release"

on:
  pull_request:
    branches:
      - master
      - Development
  push:
    branches:
      - master
      - Development

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    steps:
        #1 Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

        #2 setup java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '19'

        #3 setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

        #4 install dependencies
      - name: Install Dependencies
        run: flutter pub get

        #5 build apk
      - name: Build APK
        run: flutter build apk --debug --split-per-abi

        #10 create release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}